# netlify.toml

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENV = "production"

# Contexts let you customize per environment
[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# Force HTTPS and route admin SPA
[[redirects]]
  from = "http://*"
  to = "https://cygnas.co.uk/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Aggressive caching for hashed assets (adjust paths to your build)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
